# CONFIGURACIÓN PARA EL SERVICIO DE PERFIL (Puerto 8082)
server.port=8082

# PERSISTENCIA: Usamos un archivo distinto al de Auth para evitar bloqueos
spring.datasource.url=jdbc:h2:file:./data/perfil_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# HIBERNATE: Mantiene los datos y actualiza tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LÍMITES DE TAMAÑO: Obligatorio para que el sync de la imagen no falle
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB
